name: Build & Publish

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    publish:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Publish
              run: npm publish --provenance --access public
